#!/bin/bash
#

if [ "$(dirname $0)" != "/srv" ]; then
    mkdir -p /srv/ && cp -av $(dirname $0)/* /srv/
fi

chown -R 0:0  /srv
chmod -R 0755 /srv/update
chmod -R 0755 /srv/service
chmod -R 0755 /srv/webox/bin
chmod -R 0777 /srv/webroot/default

/srv/service stop

rm -rf /srv/webox/ready

find /srv -type f -name "*.log" -exec rm {} \;
find /srv -type f -name "*.pid" -exec rm {} \;
find /srv -type f -name "sess_*" -exec rm {} \;
find /srv -type f -name ".DS_Store" -exec rm {} \;
